# Generated by Django 5.2.7 on 2025-10-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="regression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.FloatField()),
                ("sex", models.FloatField()),
                ("bmi", models.FloatField()),
                ("children", models.FloatField()),
                ("smoker", models.FloatField()),
                ("region", models.FloatField()),
                ("charges", models.FloatField()),
            ],
        ),
    ]
