base:
  project: Techasoft
  random_state: 20
  target_col: charges

data_source:
  s3_source: data/raw/insurance.csv

load_data:
  raw_dataset_csv: data/external/insurance_clean.csv
split_data:
  train_path: data/processed/train_insurance.csv
  test_path: data/processed/test_insurance.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 1.0
      l1_ratio: 0.1
    experiment_params:
      # Simple parameter configuration - just specify the values you want to test
      # Single values for simple experiments
      alpha_values: 0.9
      l1_ratio_values: 0.3
      
      # Alternative: You can also use lists if needed
      # alpha_values: [0.1, 0.5, 1.0]
      # l1_ratio_values: [0.1, 0.5, 0.9]
      
      # Experiment settings
      max_experiments: 5  # Maximum number of parameter combinations to try
      enable_validation: true  # Validate parameter ranges

model_dirs: models/models.joblib

# reports:
#  params: reports/params.json
#  score: reports/scores.json

mlflow_config:
  artificats_dir: artificats
  experiments_name: Default
  run_name: mlops
  registered_model_name: ElasticNet
  remote_server_uri: http://127.0.0.1:5000

model_deployment:
  production_stage: "Production"
  staging_stage: "Staging"
  archived_stage: "Archived"
  metric_for_best_model: "rmse"  # Metric to use for finding best model
  sort_order: "DESC"  # DESC for highest value, ASC for lowest value

